-- Add starting map for each instance
ALTER TABLE instances ADD COLUMN IF NOT EXISTS start_map TEXT;

UPDATE instances SET start_map = 'Prontera' WHERE name = 'Altar do Selo';
UPDATE instances SET start_map = 'Malangdo' WHERE name = 'Caverna do Polvo';
UPDATE instances SET start_map = 'Malangdo' WHERE name = 'Esgotos de Malangdo';
UPDATE instances SET start_map = 'Pharos' WHERE name = 'Espaço Infinito';
UPDATE instances SET start_map = 'Rachel' WHERE name = 'Edda do Quarto Crescente';
UPDATE instances SET start_map = 'Espaço Dimensional' WHERE name = 'Torneio de Magia';
UPDATE instances SET start_map = 'Espaço Dimensional' WHERE name = 'Memórias de Sarah';
UPDATE instances SET start_map = 'Prontera' WHERE name = 'Salão de Ymir';
UPDATE instances SET start_map = 'Einbroch' WHERE name = 'Base Militar';
UPDATE instances SET start_map = 'Einbroch' WHERE name = 'Laboratório Werner';
UPDATE instances SET start_map = 'Distrito COR' WHERE name = 'Missão OS';
UPDATE instances SET start_map = 'Distrito COR' WHERE name = 'Memorial COR';
UPDATE instances SET start_map = 'Espaço Dimensional' WHERE name = 'Palácio das Mágoas';
UPDATE instances SET start_map = 'Espaço Dimensional' WHERE name = 'Sonho Sombrio';
UPDATE instances SET start_map = 'Espaço Dimensional' WHERE name = 'Invasão ao Aeroplano';
UPDATE instances SET start_map = 'Verus' WHERE name = 'Aos Pés do Rei';
UPDATE instances SET start_map = 'Espaço Dimensional' WHERE name = 'Torre do Demônio';
UPDATE instances SET start_map = 'Malaya' WHERE name = 'Caverna de Buwaya';
UPDATE instances SET start_map = 'Glastheim' WHERE name = 'Maldição de Glastheim';
UPDATE instances SET start_map = 'Glastheim' WHERE name = 'Ruína de Glastheim';
UPDATE instances SET start_map = 'Espaço Dimensional' WHERE name = 'Covil de Vermes';
UPDATE instances SET start_map = 'Verus' WHERE name = 'Laboratório Central';
UPDATE instances SET start_map = 'Lutie' WHERE name = 'Fábrica do Terror';
UPDATE instances SET start_map = 'Glastheim' WHERE name LIKE 'Queda de Glastheim%';
UPDATE instances SET start_map = 'Verus' WHERE name = 'Sala Final';
UPDATE instances SET start_map = 'Mors' WHERE name = 'Ilha Bios';
UPDATE instances SET start_map = 'Mors' WHERE name = 'Caverna de Mors';
UPDATE instances SET start_map = 'Morroc' WHERE name = 'Templo do Demônio Rei';
UPDATE instances SET start_map = 'Juno' WHERE name = 'Edda do Biolaboratório';
UPDATE instances SET start_map = 'Hugel' WHERE name = 'Ninho de Nidhogg';
UPDATE instances SET start_map = 'Lighthalzen' WHERE name = 'Laboratório de Wolfchev';
UPDATE instances SET start_map = 'Espaço Dimensional' WHERE name = 'Fortaleza Voadora';
UPDATE instances SET start_map = 'Glastheim' WHERE name = 'Glastheim Sombria';
UPDATE instances SET start_map = 'Alberta' WHERE name = 'Torre sem Fim';
UPDATE instances SET start_map = 'Payon' WHERE name = 'Cripta';
UPDATE instances SET start_map = 'Glastheim' WHERE name = 'Glastheim Infantil';
UPDATE instances SET start_map = 'Lutie' WHERE name = 'Fábrica Infantil';
UPDATE instances SET start_map = 'Geffen' WHERE name = 'Túmulo do Monarca';
UPDATE instances SET start_map = 'Malaya' WHERE name = 'Hospital Abandonado';
UPDATE instances SET start_map = 'Malaya' WHERE name = 'Lago de Bakonawa';
UPDATE instances SET start_map = 'Espaço Dimensional' WHERE name = 'Sarah vs Fenrir';
UPDATE instances SET start_map = 'Orc Village' WHERE name = 'Batalha dos Orcs';
UPDATE instances SET start_map = 'Prontera' WHERE name = 'Vila dos Porings';
